TIMERSKIPLIST_SRC_LIB := timerskiplist.c
TIMERSKIPLIST_SRC := $(TIMERSKIPLIST_SRC_LIB) timertest.c timertest2.c

TIMERSKIPLIST_SRC_LIB := $(patsubst %,$(DIRTIMERSKIPLIST)/%,$(TIMERSKIPLIST_SRC_LIB))
TIMERSKIPLIST_SRC := $(patsubst %,$(DIRTIMERSKIPLIST)/%,$(TIMERSKIPLIST_SRC))

TIMERSKIPLIST_OBJ_LIB := $(patsubst %.c,%.o,$(TIMERSKIPLIST_SRC_LIB))
TIMERSKIPLIST_OBJ := $(patsubst %.c,%.o,$(TIMERSKIPLIST_SRC))

TIMERSKIPLIST_DEP_LIB := $(patsubst %.c,%.d,$(TIMERSKIPLIST_SRC_LIB))
TIMERSKIPLIST_DEP := $(patsubst %.c,%.d,$(TIMERSKIPLIST_SRC))

CFLAGS_TIMERSKIPLIST := -I$(DIRHASHLIST) -I$(DIRMISC) -I$(DIRRANDOM)
LIBS_TIMERSKIPLIST := $(DIRRANDOM)/librandom.a

MAKEFILES_TIMERSKIPLIST := $(DIRTIMERSKIPLIST)/module.mk

.PHONY: TIMERSKIPLIST clean_TIMERSKIPLIST distclean_TIMERSKIPLIST unit_TIMERSKIPLIST $(LCTIMERSKIPLIST) clean_$(LCTIMERSKIPLIST) distclean_$(LCTIMERSKIPLIST) unit_$(LCTIMERSKIPLIST)

$(LCTIMERSKIPLIST): TIMERSKIPLIST
clean_$(LCTIMERSKIPLIST): clean_TIMERSKIPLIST
distclean_$(LCTIMERSKIPLIST): distclean_TIMERSKIPLIST
unit_$(LCTIMERSKIPLIST): unit_TIMERSKIPLIST

TIMERSKIPLIST: $(DIRTIMERSKIPLIST)/libtimerskiplist.a $(DIRTIMERSKIPLIST)/timertest $(DIRTIMERSKIPLIST)/timertest2

unit_TIMERSKIPLIST:
	@true

$(DIRTIMERSKIPLIST)/libtimerskiplist.a: $(TIMERSKIPLIST_OBJ_LIB) $(MAKEFILES_COMMON) $(MAKEFILES_TIMERSKIPLIST)
	rm -f $@
	ar rvs $@ $(filter %.o,$^)

$(DIRTIMERSKIPLIST)/timertest: $(DIRTIMERSKIPLIST)/timertest.o $(DIRTIMERSKIPLIST)/libtimerskiplist.a $(LIBS_TIMERSKIPLIST) $(MAKEFILES_COMMON) $(MAKEFILES_TIMERSKIPLIST)
	$(CC) $(CFLAGS) -o $@ $(filter %.o,$^) $(filter %.a,$^) $(CFLAGS_TIMERSKIPLIST)

$(DIRTIMERSKIPLIST)/timertest2: $(DIRTIMERSKIPLIST)/timertest2.o $(DIRTIMERSKIPLIST)/libtimerskiplist.a $(LIBS_TIMERSKIPLIST) $(MAKEFILES_COMMON) $(MAKEFILES_TIMERSKIPLIST)
	$(CC) $(CFLAGS) -o $@ $(filter %.o,$^) $(filter %.a,$^) $(CFLAGS_TIMERSKIPLIST)

$(TIMERSKIPLIST_OBJ): %.o: %.c %.d $(MAKEFILES_COMMON) $(MAKEFILES_TIMERSKIPLIST)
	$(CC) $(CFLAGS) -c -o $*.o $*.c $(CFLAGS_TIMERSKIPLIST)
	$(CC) $(CFLAGS) -c -S -o $*.s $*.c $(CFLAGS_TIMERSKIPLIST)

$(TIMERSKIPLIST_DEP): %.d: %.c $(MAKEFILES_COMMON) $(MAKEFILES_TIMERSKIPLIST)
	$(CC) $(CFLAGS) -MM -MP -MT "$*.d $*.o" -o $*.d $*.c $(CFLAGS_TIMERSKIPLIST)

clean_TIMERSKIPLIST:
	rm -f $(TIMERSKIPLIST_OBJ) $(TIMERSKIPLIST_DEP)

distclean_TIMERSKIPLIST: clean_TIMERSKIPLIST
	rm -f $(DIRTIMERSKIPLIST)/libtimerskiplist.a $(DIRTIMERSKIPLIST)/timertest $(DIRTIMERSKIPLIST)/timertest2

-include $(DIRTIMERSKIPLIST)/*.d
