LINKEDLIST_SRC_LIB := 
LINKEDLIST_SRC := $(LINKEDLIST_SRC_LIB) listtest.c

LINKEDLIST_SRC_LIB := $(patsubst %,$(DIRLINKEDLIST)/%,$(LINKEDLIST_SRC_LIB))
LINKEDLIST_SRC := $(patsubst %,$(DIRLINKEDLIST)/%,$(LINKEDLIST_SRC))

LINKEDLIST_OBJ_LIB := $(patsubst %.c,%.o,$(LINKEDLIST_SRC_LIB))
LINKEDLIST_OBJ := $(patsubst %.c,%.o,$(LINKEDLIST_SRC))

LINKEDLIST_DEP_LIB := $(patsubst %.c,%.d,$(LINKEDLIST_SRC_LIB))
LINKEDLIST_DEP := $(patsubst %.c,%.d,$(LINKEDLIST_SRC))

CFLAGS_LINKEDLIST := -I$(DIRHASHLIST) -I$(DIRMISC)

MAKEFILES_LINKEDLIST := $(DIRLINKEDLIST)/module.mk

.PHONY: LINKEDLIST clean_LINKEDLIST distclean_LINKEDLIST unit_LINKEDLIST $(LCLINKEDLIST) clean_$(LCLINKEDLIST) distclean_$(LCLINKEDLIST) unit_$(LCLINKEDLIST)

$(LCLINKEDLIST): LINKEDLIST
clean_$(LCLINKEDLIST): clean_LINKEDLIST
distclean_$(LCLINKEDLIST): distclean_LINKEDLIST

LINKEDLIST: $(DIRLINKEDLIST)/liblinkedlist.a $(DIRLINKEDLIST)/listtest

unit_LINKEDLIST: $(DIRLINKEDLIST)/listtest
	$(DIRLINKEDLIST)/listtest

$(DIRLINKEDLIST)/liblinkedlist.a: $(LINKEDLIST_OBJ_LIB) $(MAKEFILES_COMMON) $(MAKEFILES_LINKEDLIST)
	rm -f $@
	ar rvs $@ $(filter %.o,$^)

$(DIRLINKEDLIST)/listtest: $(DIRLINKEDLIST)/listtest.o $(DIRLINKEDLIST)/liblinkedlist.a $(MAKEFILES_COMMON) $(MAKEFILES_LINKEDLIST)
	$(CC) $(CFLAGS) -o $@ $(filter %.o,$^) $(filter %.a,$^) $(CFLAGS_LINKEDLIST)

$(LINKEDLIST_OBJ): %.o: %.c $(LINKEDLIST_DEP) $(MAKEFILES_COMMON) $(MAKEFILES_LINKEDLIST)
	$(CC) $(CFLAGS) -c -o $*.o $*.c $(CFLAGS_LINKEDLIST)

$(LINKEDLIST_DEP): %.d: %.c $(MAKEFILES_COMMON) $(MAKEFILES_LINKEDLIST)
	$(CC) $(CFLAGS) -MM -MP -MT "$*.d $*.o" -o $*.d $*.c $(CFLAGS_LINKEDLIST)

clean_LINKEDLIST:
	rm -f $(LINKEDLIST_OBJ) $(LINKEDLIST_DEP)

distclean_LINKEDLIST: clean_LINKEDLIST
	rm -f $(DIRLINKEDLIST)/liblinkedlist.a $(DIRLINKEDLIST)/containeroftest

-include $(LINKEDLIST_DEP)
