TIMERWHEEL_SRC_LIB := timerwheel.c
TIMERWHEEL_SRC := $(TIMERWHEEL_SRC_LIB) timertest.c timerperf.c

TIMERWHEEL_SRC_LIB := $(patsubst %,$(DIRTIMERWHEEL)/%,$(TIMERWHEEL_SRC_LIB))
TIMERWHEEL_SRC := $(patsubst %,$(DIRTIMERWHEEL)/%,$(TIMERWHEEL_SRC))

TIMERWHEEL_OBJ_LIB := $(patsubst %.c,%.o,$(TIMERWHEEL_SRC_LIB))
TIMERWHEEL_OBJ := $(patsubst %.c,%.o,$(TIMERWHEEL_SRC))

TIMERWHEEL_DEP_LIB := $(patsubst %.c,%.d,$(TIMERWHEEL_SRC_LIB))
TIMERWHEEL_DEP := $(patsubst %.c,%.d,$(TIMERWHEEL_SRC))

CFLAGS_TIMERWHEEL := -I$(DIRHASHLIST) -I$(DIRMISC) -I$(DIRLINKEDLIST)

MAKEFILES_TIMERWHEEL := $(DIRTIMERWHEEL)/module.mk

.PHONY: TIMERWHEEL clean_TIMERWHEEL distclean_TIMERWHEEL unit_TIMERWHEEL $(LCTIMERWHEEL) clean_$(LCTIMERWHEEL) distclean_$(LCTIMERWHEEL) unit_$(LCTIMERWHEEL)

$(LCTIMERWHEEL): TIMERWHEEL
clean_$(LCTIMERWHEEL): clean_TIMERWHEEL
distclean_$(LCTIMERWHEEL): distclean_TIMERWHEEL
unit_$(LCTIMERWHEEL): unit_TIMERWHEEL

TIMERWHEEL: $(DIRTIMERWHEEL)/libtimerwheel.a $(DIRTIMERWHEEL)/timertest $(DIRTIMERWHEEL)/timerperf

unit_TIMERWHEEL:
	@true

$(DIRTIMERWHEEL)/libtimerwheel.a: $(TIMERWHEEL_OBJ_LIB) $(MAKEFILES_COMMON) $(MAKEFILES_TIMERWHEEL)
	rm -f $@
	ar rvs $@ $(filter %.o,$^)

$(DIRTIMERWHEEL)/timertest: $(DIRTIMERWHEEL)/timertest.o $(DIRTIMERWHEEL)/libtimerwheel.a $(MAKEFILES_COMMON) $(MAKEFILES_TIMERWHEEL)
	$(CC) $(CFLAGS) -o $@ $(filter %.o,$^) $(filter %.a,$^) $(CFLAGS_TIMERWHEEL)

$(DIRTIMERWHEEL)/timerperf: $(DIRTIMERWHEEL)/timerperf.o $(DIRTIMERWHEEL)/libtimerwheel.a $(MAKEFILES_COMMON) $(MAKEFILES_TIMERWHEEL)
	$(CC) $(CFLAGS) -o $@ $(filter %.o,$^) $(filter %.a,$^) $(CFLAGS_TIMERWHEEL)

$(TIMERWHEEL_OBJ): %.o: %.c %.d $(MAKEFILES_COMMON) $(MAKEFILES_TIMERWHEEL)
	$(CC) $(CFLAGS) -c -o $*.o $*.c $(CFLAGS_TIMERWHEEL)
	$(CC) $(CFLAGS) -c -S -o $*.s $*.c $(CFLAGS_TIMERWHEEL)

$(TIMERWHEEL_DEP): %.d: %.c $(MAKEFILES_COMMON) $(MAKEFILES_TIMERWHEEL)
	$(CC) $(CFLAGS) -MM -MP -MT "$*.d $*.o" -o $*.d $*.c $(CFLAGS_TIMERWHEEL)

clean_TIMERWHEEL:
	rm -f $(TIMERWHEEL_OBJ) $(TIMERWHEEL_DEP)

distclean_TIMERWHEEL: clean_TIMERWHEEL
	rm -f $(DIRTIMERWHEEL)/libtimerwheel.a $(DIRTIMERWHEEL)/timertest $(DIRTIMERWHEEL)/timerperf

-include $(DIRTIMERWHEEL)/*.d
