TOPLEVEL:=..
MODULE:=DYNARR

all:
	cd $(TOPLEVEL); $(MAKE) $(MODULE)

clean:
	cd $(TOPLEVEL); $(MAKE) clean_$(MODULE)

distclean:
	cd $(TOPLEVEL); $(MAKE) distclean_$(MODULE)

unit:
	cd $(TOPLEVEL); $(MAKE) unit_$(MODULE)
